try {
    throw new Error("Se ha producido un error", "ejercicio13.js", 100);
  } catch (error) {
    console.error(error);
  }


  